### ISSUE TITLE
Village is Destroyed

### ISSUE THREAD

**Issue by Bartz45** [sme23/bsfe#1]
In the Chapter with Minerva and Hardin, if Est visits the village, it is destroyed after she gets the item.
![2019-03-06 7](https://user-images.githubusercontent.com/48301050/53922131-73236300-4049-11e9-8aaf-3eda34653953.png)

**Comment by sme23** [comment]
fixed in commit f228ef8dcc296c938be70b35ed532fcbff2f3bde
