### ISSUE TITLE
'Win' In the Menu

### ISSUE THREAD

**Issue by Bartz45** [sme23/bsfe#11]
![2019-03-07 1](https://user-images.githubusercontent.com/48301050/53961813-ebc50680-40bf-11e9-8f1b-9f2064d7b346.png)

Now, on the menu, 'Win' is an option. For someone who actually wants to play the chapter, it is frustrating when you are trying to proceed through the chapter, and you select 'Win' by mistake, ending the chapter.

**Comment by sme23** [comment]
fixed in release tied to commit 8679ccac0a50a6e016822e305561f4ca0d958bc8
