### ISSUE TITLE
Nyna is Weak to Bows 

### ISSUE THREAD

**Issue by Bartz45** [sme23/bsfe#2]
Nyna is extremely weak to bows in the entirety of Chapter 1. Weapon glows indicating an exponential amount of damage is to be dealt.
![screenshot_20190306-182710_john_gba_lite](https://user-images.githubusercontent.com/48301050/53922228-d614fa00-4049-11e9-8519-a513436743f4.jpg)

**Comment by sme23** [comment]
fixed in commit f228ef8dcc296c938be70b35ed532fcbff2f3bde
