### ISSUE TITLE
Freezing at Staff Selection

### ISSUE THREAD

**Issue by Bartz45** [sme23/bsfe#3]
Any Cleric/Bishop style units that try to use a Heal/Mend staff are unable to do so, as the game freezes as the item window opens up.
![2019-03-06 11](https://user-images.githubusercontent.com/48301050/53922409-900c6600-404a-11e9-8e61-6e2c61c2771f.png)

![2019-03-06 3](https://user-images.githubusercontent.com/48301050/53922414-926ec000-404a-11e9-8fd9-64c6b06a7117.png)
Something else here, Boah's portrait is misaligned just a bit, right to the left edge of the box under his portrait.

**Comment by sme23** [comment]
Fixed with commit a2ff542eeafc2f2356c5012ff57f68340453d973
