### ISSUE TITLE
Trading Issues 

### ISSUE THREAD

**Issue by Bartz45** [sme23/bsfe#4]
Units are unable to trade items, the second the option is selected, the screen looks like this: 
![screenshot_20190306-183706_john_gba_lite](https://user-images.githubusercontent.com/48301050/53922499-fd1ffb80-404a-11e9-84b5-4cad4c35102d.jpg)

**Comment by sme23** [comment]
Trading fixed with commit a2ff542eeafc2f2356c5012ff57f68340453d973, graphical issue still present but falls under issue #5
