### ISSUE TITLE
Graphical Glitches 

### ISSUE THREAD

**Issue by Bartz45** [sme23/bsfe#5]
1. For this one, it happens if Boah's portrait shows up in parts on the screen, then one of the armor knights enters a battle. Boah's portrait may show up in parts after examining his inventory.
![screenshot_20190306-185354_my_boy_free](https://user-images.githubusercontent.com/48301050/53922527-1e80e780-404b-11e9-8284-e86dd3d79f7d.jpg)

![screenshot_20190306-185740_my_boy_free](https://user-images.githubusercontent.com/48301050/53922570-512ae000-404b-11e9-9ccc-db61ede22965.jpg)

2. If Roshea dies, the portrait is regular GBA sized, and the textbox is glitched.
![2019-03-06 8](https://user-images.githubusercontent.com/48301050/53922664-9d762000-404b-11e9-9cec-e4a17d3925b6.png)

3. For Malice, there are stray pixels under her Lady Sword once her inventory is opened by pressing R. 
![2019-03-06 10](https://user-images.githubusercontent.com/48301050/53922683-b8489480-404b-11e9-93b1-81ba9d0fb5a9.png)

4a. Poor Catria has a terrible mug full of glitches: 
![2019-03-06 5](https://user-images.githubusercontent.com/48301050/53922701-cf878200-404b-11e9-9704-1dfb76922f83.png)

4b. Catria's mug is also glitched in the stat - screen as well: 
![2019-03-06 6](https://user-images.githubusercontent.com/48301050/53922726-e8903300-404b-11e9-8dff-21b407c2b0a3.png)

**Comment by KaidenMelon** [comment]
![fire emblem - the sacred stones gba](https://user-images.githubusercontent.com/48302688/53925634-4d488f00-4046-11e9-9f98-bc04efa527f8.png)
 this happend, random stray pixels under Gouber's steel lance. I don't know what caused it but every time i've loaded up the chapter its been there.

**Comment by sme23** [comment]
Fixed in major restructure
