### ISSUE TITLE
Stat Screen Glitches 

### ISSUE THREAD

**Issue by Bartz45** [sme23/bsfe#9]
Stray pixels are under the weapons of the enemy soldiers. 
![2019-03-07 4](https://user-images.githubusercontent.com/48301050/53961400-dd2a1f80-40be-11e9-8cd7-c39b8fe952c9.png)
![2019-03-07 2](https://user-images.githubusercontent.com/48301050/53961403-ddc2b600-40be-11e9-8e61-4138356dfb5c.png)
![2019-03-07 3](https://user-images.githubusercontent.com/48301050/53961404-ddc2b600-40be-11e9-915a-9fe73a7a0e52.png)

Additionally, the boss of the chapter, when he talks/blinks, his ear blinks as well? (I don't know how to word that, it just looks weird.)

**Comment by sme23** [comment]
This is something tied to halfbodies that I've yet to find. Should eventually be fixed, but for now labelled as bug.

**Comment by sme23** [comment]
actually this is already addressed in issue #5 so gonna close this one
